### ISSUE TITLE
Error in symmetryReduceKpointList

### ISSUE THREAD

**Issue by JohnEdChristensen** [msg-byu/kgridGen#16] opened 2018-05-14 16:06 UTC
I encountered the following error when reducing k-points with `generateIrredKpointList`:
```
 ERROR: (symmetryReduceKpointList in generateKpoints.f90)
 The length of an orbit did not divide the group size
Group size:  4   Orbit length:  3
```
Here are the parameters in `generateIrredKpointList` before being passed to `symmetryReduceKpointList`:
```
 A
   1.0000000000000000        1.0000000000000000        1.0000000000000000     
   1.2247448700000001       -1.2247448700000001       -1.0000000000000000     
 -0.16598509000000000       -1.6430829700000000        1.8090680600000000
     
 Atom labels:           0

 AtBas
   0.0000000000000000        0.0000000000000000        0.0000000000000000     
 
K
  0.47497680660440167       0.25229592053480804       0.27272727286079029     
  0.21246520990660386      -0.12155611919778875       -9.0909090708815130E-002
 -0.10629664241000890        6.0144154125115687E-002   4.6152488284893219E-002

 R
  0.47497680660440217       0.25229592053480782       0.27272727286079013     
  0.42493041981320634      -0.24311223839557669      -0.18181818141762968     
  -2.7664181297411120E-002 -0.27384716467239190       0.30151134596980300     
```

**Comment by glwhart** [comment] 2018-05-14 21:04
Is 0 the label for the first atom? This definitely looks like a finite precision error to me...this is good for a bounty if we can verify that it's really a bug (which I'm pretty sure it is...)

**Comment by JohnEdChristensen** [comment] 2018-05-14 21:31
Yes that is the label

**Comment by glwhart** [comment] 2018-05-15 20:49
The likely problem is that there should be 4 kpoints on a single orbit (that is, 4 equivalent points), but one of them was not detected as equivalent because of a finite precision error. Do you think you can figure that out? Jeremy could probably help you if you get stuck.

I'm awarding $20 bounty for this bug. Another $20 if you can fix it...

**Comment by wsmorgan** [comment] 2018-06-29 20:00
I've found this bug again trying to fold one of Time Mueller's grids:
```
 ERROR: (symmetryReduceKpointList in generateKpoints.f90)
 The length of an orbit did not divide the group size
Group size:  8   Orbit length:  3
 ERROR: (symmetryReduceKpointList in generateKpoints.f90)
 The length of an orbit did not divide the group size
Group size:  8   Orbit length:  3
 ERROR: (symmetryReduceKpointList in generateKpoints.f90)
 The length of an orbit did not divide the group size
Group size:  8   Orbit length:  7
 ERROR: (symmetryReduceKpointList in generateKpoints.f90)
 The length of an orbit did not divide the group size
Group size:  8   Orbit length:  7
 found this many k-points         168
 found this many irreducible k-points          48
```
I will also note that when Mueller folds this grid he gets 44 irreducible k-points just as a reference.

Here is the driver I used to hit the bug:
```
PROGRAM kpoint_driver
  use kpointGeneration
  use num_types
  use vector_matrix_utilities
  use symmetry, only : get_lattice_pointGroup
  use rational_mathematics, only: HermiteNormalForm
  implicit none  
  real(dp)              :: K(3,3), R(3,3), Hinv(3,3), eps, shift(3), H(3,3)
  real(dp), pointer     :: klist(:,:)
  real(dp), pointer     :: pgOps(:,:,:), rdKlist(:,:)
  integer, pointer      :: weights(:)
  real(dp), pointer :: atbase(:,:)
  integer :: at(8)
  integer i


  real(dp) :: lat(3,3), lat_inv(3,3)
  logical :: err

  allocate(atbase(3,8))
  shift = (/ 0.0_dp, 0.0_dp, 0.0_dp /)

  lat(:,1) = (/0.5_dp, 0.5_dp, 0.0_dp/)
  lat(:,2) = (/0.5_dp, -0.5_dp, 2.0_dp/)
  lat(:,3) = (/1.0_dp, -1.0_dp, 0.0_dp/)
  at = (/0, 0, 0, 1, 1, 1, 1, 1/)

  atbase(:,1) = (/0.0_dp,0.0_dp,0.0_dp/)
  atbase(:,2) = (/0.5_dp, 0.25_dp, 0.125_dp/)
  atbase(:,3) = (/0.5_dp, 0.75_dp, 0.375_dp/)
  atbase(:,4) = (/0.0_dp, 0.5_dp, 0.25_dp/)
  atbase(:,5) = (/0.0_dp, 0.0_dp, 0.5_dp/)
  atbase(:,6) = (/0.5_dp, 0.25_dp, 0.625_dp/)
  atbase(:,7) = (/0.0_dp, 0.5_dp, 0.75_dp/)
  atbase(:,8) = (/0.5_dp, 0.75_dp, 0.875_dp/)

  call matrix_inverse(lat, lat_inv, err)

  R = transpose(lat_inv)
  
  K(:,1) = (/-0.0714285714_dp,  -0.0714285714_dp,   0.125000000_dp/)
  K(:,2) = (/ 0.0119047619_dp,  -0.154761905_dp,  0.0_dp/)
  K(:,3) = (/0.154761905_dp,  -0.0119047619_dp,  0.0_dp/)

  ! K(:,1) = (/0.14285714285714285_dp, 0.14285714285714285_dp,        0.0_dp/)
  ! K(:,2) = (/-0.15476190476190477_dp, 0.011904761904761904_dp, 0.083333333333333329_dp/)
  ! K(:,3) = (/0.25000000000000000_dp, -0.25000000000000000_dp, -0.12500000000000000_dp/)
  eps = 1e-3_dp
  call generateFullKpointList(K, R, shift, klist, eps)
  call generateIrredKpointList(lat, atbase, at, K, R, shift, rdKlist, weights, eps)
  print *, "found this many k-points", size(klist,1)
  print *, "found this many irreducible k-points", size(rdKlist,1)
  
END PROGRAM kpoint_driver
```

**Comment by wsmorgan** [comment] 2018-06-29 20:01
I also cycled through eps values between 1E-2, 1E-3, 1E-6, and 1E-10, they all either are to strict/loose for the code to run or return the above errors.

**Comment by jerjorg** [comment] 2018-07-02 19:10
I took a crack at John's bug. Here is my driver.
```
PROGRAM kpoint_driver
  use kpointGeneration
  use num_types
  use vector_matrix_utilities
  use symmetry, only : get_lattice_pointGroup, get_spaceGroup
  use rational_mathematics, only: HermiteNormalForm
  use fortpy
  implicit none  
  real(dp)               :: lat_vecs(3,3), rlat_vecs(3,3), eps, shift(3), grid_vecs(3,3)
  real(dp), pointer      :: sg_op(:,:,:)
  real(dp), pointer      :: sg_fract(:,:)
  integer, pointer       :: atom_labels(:)
  real(dp), pointer      :: atom_positions(:,:)
  logical                :: lattcoords  
  ! real(dp)              :: Hinv(3,3), H(3,3)
  real(dp), pointer      :: klist(:,:)  
  real(dp), pointer      :: rdKlist(:,:)! , pgOps(:,:,:), 
  integer, pointer       :: weights(:)
  
  lat_vecs = transpose(reshape((/ 1.0_dp, 1.22474487_dp, -0.16598509_dp, &
                            1.0_dp, -1.22474487_dp, -1.64308297_dp, &
                            1.0_dp, -1.0_dp, 1.80906806_dp /),(/3,3/)))
  rlat_vecs = transpose(reshape((/ 0.474976806604402_dp, 0.424930419813206_dp, -0.027664181297411_dp, &
                            0.252295920534808_dp, -0.243112238395577_dp, -0.273847164672392_dp, &
                            0.27272727286079_dp, -0.18181818141763_dp, 0.301511345969803_dp /),(/3,3/)))
  allocate(atom_labels(1:1))
  allocate(atom_positions(1:3, 1:1))
  atom_labels = (/ 0 /)
  atom_positions = transpose(reshape((/ 0, 0, 0 /), (/1,3/)))
  grid_vecs = transpose(reshape((/ 0.474976806604402, 0.212465209906604, -0.106296642410009, &
                            0.252295920534808, -0.121556119197789, 0.060144154125116, &
                            0.27272727286079, -0.090909090708815, 0.046152488284893 /),(/3,3/)))
  shift = (/ 0_dp, 0_dp, 0_dp /)
  
  lattcoords = .true.
  eps = 1e-6_dp
  call get_spaceGroup(lat_vecs, atom_labels, atom_positions, sg_op, sg_fract, lattcoords, eps)
   
  call generateFullKpointList(grid_vecs, rlat_vecs, shift, klist, eps)

  call generateIrredKpointList(lat_vecs, atom_positions, atom_labels, grid_vecs, &
                               & rlat_vecs, shift, rdKlist, weights, eps)

  write(*, '(//)')
  write(*, '("Unrd kpts: ", i7)') size(klist, 1)
  write(*, '("Rdcd kpts: ", i7)') size(rdKlist, 1)
  write(*, '("Rdn ratio: ", 3x, f4.1)') size(klist, 1) / real( size(weights) )
  
  deallocate(atom_labels)
  deallocate(atom_positions)  
  
END PROGRAM kpoint_driver
```

I kept getting the error `STOP The point generating vectors and the reciprocal lattice are incommensurate.`. The integer matrix that relates the grid and reciprocal lattice bases was
```
0.99999999999995270        2.2565282975506307E-014   1.6093270666650561E-006  
-6.3626483353118601E-006   2.0000031480112597        216.00021961127334       
-1.2706075040114229E-005   6.3268962549045682E-006   432.00044499680263 
```
This was the same thing I was getting in Python except all the numbers were much closer to integers. When I changed the optional, absolute tolerance for `equal` (I hard coded a value directly into the code) to 1e-4 for `generateFullKpointList`, I no longer got this error.

I then got the error `The k-point is not a lattice point of the generating vectors.` from `findKptIndex`, which is called by `symmetryReduceKpointList`. The point that set off the error was `2.2565282975506307E-014   2.0000031480112597        2.0000063268962549`, which is a lattice point with a lot of finite precision error. I increased the absolute tolerance of `findKptIndex` to 1e-3, the code ran without error, and gave the output
```
Unrd kpts:     864
Rdcd kpts:     828
Rdn ratio:     1.0
```

I'm not able to reproduce John's error. Was this error fixed by the long integer fix? I really think that the user should be able to adjust the absolute and relative tolerances.

**Comment by jerjorg** [comment] 2018-07-02 19:53
It's the exact same story for Wiley's similar bug above. Here is the driver.
```
PROGRAM kpoint_driver
  use kpointGeneration
  use num_types
  use vector_matrix_utilities
  use symmetry, only : get_lattice_pointGroup, get_spaceGroup
  use rational_mathematics, only: HermiteNormalForm
  use fortpy
  implicit none  
  real(dp)               :: lat_vecs(3,3), rlat_vecs(3,3), eps, shift(3), grid_vecs(3,3)
  real(dp), pointer      :: sg_op(:,:,:)
  real(dp), pointer      :: sg_fract(:,:)
  integer, pointer       :: atom_labels(:)
  real(dp), pointer      :: atom_positions(:,:)
  logical                :: lattcoords  
  ! real(dp)              :: Hinv(3,3), H(3,3)
  real(dp), pointer      :: klist(:,:)  
  real(dp), pointer      :: rdKlist(:,:)! , pgOps(:,:,:), 
  integer, pointer       :: weights(:)
  
  lat_vecs = transpose(reshape((/ 0.5_dp, 0.5_dp, 1.0_dp, &
                            0.5_dp, -0.5_dp, -1.0_dp, &
                            0.0_dp, 2.0_dp, 0.0_dp /),(/3,3/)))
  rlat_vecs = transpose(reshape((/ 1.0_dp, 0.0_dp, 0.5_dp, &
                            1.0_dp, 0.0_dp, -0.5_dp, &
                            0.0_dp, 0.5_dp, -0.25_dp /),(/3,3/)))
  allocate(atom_labels(1:8))
  allocate(atom_positions(1:3, 1:8))
  atom_labels = (/ 0, 0, 0, 1, 1, 1, 1, 1 /)
  atom_positions = transpose(reshape((/ 0.0, 0.0, 0.0, &
                            0.5, 0.25, 0.125, &
                            0.5, 0.75, 0.375, &
                            0.0, 0.5, 0.25, &
                            0.0, 0.0, 0.5, &
                            0.5, 0.25, 0.625, &
                            0.0, 0.5, 0.75, &
                            0.5, 0.75, 0.875 /),(/8,3/)))
  grid_vecs = transpose(reshape((/ -0.0714285714, 0.0119047619, 0.154761905, &
                            -0.0714285714, -0.154761905, -0.0119047619, &
                            0.125, 0.0, 0.0 /),(/3,3/)))
  shift = (/ 0_dp, 0_dp, 0_dp /)

  lattcoords = .true.
  eps = 1e-6_dp
  call get_spaceGroup(lat_vecs, atom_labels, atom_positions, sg_op, sg_fract, lattcoords, eps)
  
  call generateFullKpointList(grid_vecs, rlat_vecs, shift, klist, eps)

  call generateIrredKpointList(lat_vecs, atom_positions, atom_labels, grid_vecs, &
                               & rlat_vecs, shift, rdKlist, weights, eps)

  write(*, '(//)')
  write(*, '("nops: ", i7)') size(sg_op, 1)
  write(*, '("Unrd kpts: ", i7)') size(klist, 1)
  write(*, '("Rdcd kpts: ", i7)') size(rdKlist, 1)
  write(*, '("Rdn ratio: ", 3x, f4.1)') size(klist, 1) / real( size(weights) )

  deallocate(atom_labels)
  deallocate(atom_positions)  
  
END PROGRAM kpoint_driver
```

I fixed the error `STOP The point generating vectors and the reciprocal lattice are incommensurate.` by changing the absolute tolerance in `generateFullKpointList` to 1e-4. I then got the error `The k-point is not a lattice point of the generating vectors.`, which I fixed by changing the absolute tolerance in `findKptIndex` to 1e-5. Here is the output.
```
nops:       3
Unrd kpts:     168
Rdcd kpts:     168
Rdn ratio:     1.0
```

It was surprising that there wasn't any symmetry reduction. The Python code went from 168 to 69 k-points or a symmetry reduction ratio of  2.4, around what you would expect with 3 operators. My Python code also got a different reduction ratio for John's error, going from 864 to 326 k-points, an unsurprising ratio of 2.65. There must be another bug elsewhere in the code.

**Comment by wsmorgan** [comment] 2018-08-10 21:17
Some of our issues actually appear to be related to a bug in `symlib` [Issue #19](https://github.com/msg-byu/symlib/issues/19).

**Comment by jerjorg** [comment] 2019-07-18 05:11
It appears that the fix in symlib solved this issue. Here's a driver for John's bug
```
PROGRAM kpoint_driver
  use kpointGeneration
  use num_types
  use vector_matrix_utilities
  use symmetry, only : get_lattice_pointGroup, get_spaceGroup
  use rational_mathematics, only: HermiteNormalForm
  implicit none
  real(dp)               :: lat_vecs(3,3), rlat_vecs(3,3), eps, shift(3), grid_vecs(3,3)
  real(dp), allocatable  :: sg_op(:,:,:)
  real(dp), allocatable  :: sg_fract(:,:)
  integer, pointer       :: atom_labels(:)
  real(dp), allocatable  :: atom_positions(:,:)
  logical                :: lattcoords
  ! real(dp)              :: Hinv(3,3), H(3,3)
  real(dp), pointer      :: klist(:,:)
  real(dp), pointer      :: rdKlist(:,:)! , pgOps(:,:,:),
  integer, pointer       :: weights(:)

  lat_vecs(:,1) = (/ 1.0_dp, 1.0_dp, 1.0_dp /)
  lat_vecs(:,2) = (/ 1.2247448700000001_dp, -1.2247448700000001_dp, -1.0_dp /)
  lat_vecs(:,3) = (/ -0.16598509_dp, -1.64308297_dp, 1.80906806_dp /)

  rlat_vecs(:,1) = (/ 0.47497680660440217_dp,  0.25229592053480782_dp,  0.27272727286079013_dp /)
  rlat_vecs(:,2) = (/ 0.42493041981320634_dp, -0.24311223839557669_dp, -0.18181818141762968_dp /)
  rlat_vecs(:,3) = (/ -2.7664181297411120E-002_dp, -0.27384716467239190_dp, 0.30151134596980300_dp /)

  grid_vecs(:,1) = (/ 0.47497680660440167_dp, 0.25229592053480804_dp,  0.27272727286079029_dp /)
  grid_vecs(:,2) = (/ 0.21246520990660386_dp, -0.12155611919778875_dp, -9.0909090708815130E-002_dp /)
  grid_vecs(:,3) = (/ -0.10629664241000890_dp, 6.0144154125115687E-002_dp, 4.6152488284893219E-002_dp /)

  allocate(atom_labels(1:1))
  allocate(atom_positions(3,1))
  atom_labels = (/ 0 /)
  atom_positions(:,1) = (/ 0.0_dp, 0.0_dp, 0.0_dp /)
  shift = (/ 0_dp, 0_dp, 0_dp /)

  lattcoords = .true.
  eps = 1e-3_dp
  call get_spaceGroup(lat_vecs, atom_labels, atom_positions, sg_op, sg_fract, lattcoords, eps)

  call generateFullKpointList(grid_vecs, rlat_vecs, shift, klist, eps)

  call generateIrredKpointList(lat_vecs, atom_positions, atom_labels, grid_vecs, &
                               & rlat_vecs, shift, rdKlist, weights, eps)

  write(*, '(//)')
  write(*, '("Unrd kpts: ", i7)') size(klist, 1)
  write(*, '("Rdcd kpts: ", i7)') size(rdKlist, 1)
  write(*, '("Rdn ratio: ", 3x, f4.1)') size(klist, 1) / real( size(weights) )

  deallocate(atom_labels)
  deallocate(atom_positions)

END PROGRAM kpoint_driver
```
and its output
```
numops           4
numops           4

Unrd kpts:     864
Rdcd kpts:     326
Rdn ratio:     2.7
```
Running the driver Wiley posted above gives
```
numops           8
 found this many k-points         168
 found this many irreducible k-points          44
```
which gives the same number of reduced k-points as Mueller.

**Closed as completed by jerjorg** 2019-07-18 05:11 UTC
Labels: bug
